// gamerat-gui ESLint flat config.
//
// Layered defaults, no surprises:
//   1. `@eslint/js`            — baseline JS rules
//   2. typescript-eslint       — recommended everywhere, strict +
//                                stylistic with type information on
//                                app sources only (src/**)
//   3. eslint-plugin-sonarjs   — bug + maintainability heuristics
//   4. eslint-plugin-unicorn   — modern-idiom enforcement
//   5. eslint-plugin-security  — security smells
//   6. eslint-plugin-svelte    — Svelte 5 component rules
//
// Type-aware rules are scoped to `src/**` so the surrounding config
// files (vite.config.ts, svelte.config.js, this file) don't need to
// live in the tsconfig project graph.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import sonarjs from 'eslint-plugin-sonarjs';
import unicorn from 'eslint-plugin-unicorn';
import security from 'eslint-plugin-security';
import svelte from 'eslint-plugin-svelte';
import svelteParser from 'svelte-eslint-parser';
import globals from 'globals';

export default tseslint.config(
    {
        ignores: [
            'build/',
            'dist/',
            'node_modules/',
            'src-tauri/',
            '.svelte-kit/',
            '.vite/',
            'pnpm-lock.yaml',
            // Generated by Paraglide on compile (see `messages` script).
            'src/lib/paraglide/',
        ],
    },

    // Baseline (all files).
    js.configs.recommended,
    sonarjs.configs.recommended,
    unicorn.configs.recommended,
    security.configs.recommended,

    // Non-type-aware typescript-eslint everywhere — gives us the right
    // parser for any .ts file, syntax rules, no project lookup.
    ...tseslint.configs.recommended,

    // Type-aware strict + stylistic rules: scoped to src/.
    {
        files: ['src/**/*.{ts,svelte}'],
        extends: [
            ...tseslint.configs.strictTypeChecked,
            ...tseslint.configs.stylisticTypeChecked,
        ],
        languageOptions: {
            globals: { ...globals.browser },
            parserOptions: {
                projectService: true,
                tsconfigRootDir: import.meta.dirname,
                extraFileExtensions: ['.svelte'],
            },
        },
    },

    // Svelte parser handoff for component files.
    ...svelte.configs.recommended,
    {
        files: ['src/**/*.svelte'],
        languageOptions: {
            parser: svelteParser,
            parserOptions: {
                parser: tseslint.parser,
                svelteFeatures: { runes: true },
            },
        },
        rules: {
            // `no-top-level-assignment-in-function` (new in unicorn 68) is a
            // sound guard for plain modules, but it fundamentally misreads
            // Svelte 5: reassigning a top-level `$state` rune from inside an
            // event handler or effect is *the* reactivity idiom, not a smell.
            // Kept on for `.ts`/`.js`; off for components.
            'unicorn/no-top-level-assignment-in-function': 'off',
        },
    },

    // Project-wide rule tweaks.
    {
        rules: {
            // Repo convention: kebab-case filenames, Svelte components
            // PascalCase. `vite-env.d.ts` and `App.svelte` both fit.
            'unicorn/filename-case': [
                'error',
                {
                    cases: { kebabCase: true, pascalCase: true },
                },
            ],
            // `null` is a useful "not yet" sentinel in component state.
            'unicorn/no-null': 'off',
            // `req`/`env`/`prop`/`args` are vernacular here; the rule
            // is famously over-eager and produces more noise than value.
            'unicorn/prevent-abbreviations': 'off',
            // `name-replacements` (new in unicorn 68) is the same complaint
            // as `prevent-abbreviations` from a different angle — it flags
            // `res`/`cmd`/`env` etc. Same stance: intentional vernacular.
            'unicorn/name-replacements': 'off',
            // `consistent-boolean-name` (new in unicorn 68) throws
            // `TypeError: parameters is not iterable` on the
            // svelte-eslint-parser AST (findParameter assumes every
            // `Parameter` definition carries a `params` array). It crashes
            // the whole lint run, so it can't be enforced regardless of
            // merit — disabled until upstream guards the non-standard shape.
            'unicorn/consistent-boolean-name': 'off',
        },
    },

    // Config files: Node globals, no project-graph requirement.
    {
        files: ['*.config.{js,ts}', 'eslint.config.js', 'svelte.config.js'],
        languageOptions: {
            globals: { ...globals.node },
        },
        rules: {
            'no-console': 'off',
        },
    },

    // Playwright a11y suite (tests/**). Lives outside src/** so it stays
    // on the non-type-aware path (no tsconfig project entry needed). Runs
    // in Node (the test runner) but its `page.evaluate`/`addInitScript`
    // bodies execute in the browser, so both global sets are in scope.
    {
        files: ['tests/**/*.ts'],
        languageOptions: {
            globals: { ...globals.node, ...globals.browser },
        },
        rules: {
            // The Tauri mock dispatches on a fixture table keyed by the
            // incoming command name — an intentional dynamic lookup over a
            // local constant, not user-controlled property access.
            'security/detect-object-injection': 'off',
        },
    },
);
